services:
  redis:
    image: redis:7-alpine
    command: redis-server
    ports:
      - 6379:6379
    networks:
      local-network:
        ipv4_address: 172.28.1.4

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game-engine
    ports:
      - 5432:5432
    networks:
      local-network:
        ipv4_address: 172.28.1.5

  game-engine:
    build: ./
    ports:
      - 80:4000
    depends_on:
      - postgres
      - redis
    networks:
      - local-network

networks:
  local-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
